title: 'Lucy Tumolo RMT'
default_lang: en
author:
  name: 'Lucy Tumolo'
  email: me@jamieguerrero.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Lucy Tumolo is a registered massage therapist based in the GTA'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
