stages:
  - deploy

before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

deploy_stage:
  stage: deploy
  environment:
    name: staging
    url: https://www.jamieguerrero.com/gitlab
  only:
    - master
  script:
    - ls
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - echo $USER_PASS
    - sshpass -e scp -P 18765 -o stricthostkeychecking=no -r .  jamiegue@jamieguerrero.com:/gitlab
